services:

  discovery-service:
    build: ./discovery-service
    container_name: myapp-discovery-service
    ports:
      - '8761:8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      retries: 8

  config-service:
    build: ./config-service
    container_name: myapp-config-service
    ports:
      - '9999:9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 5s
      retries: 8

#  customer-service:
#    build: ./customer-service
#    container_name: myapp-customer-service
#    ports:
#      - '8081:8081'
#    environment:
#      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
#      - CONFIG_SERVICE_URL=http://config-service:9999
#    depends_on:
#      config-service:
#        condition: service_healthy
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
#      interval: 5s
#      retries: 8

  gateway-service:
    build: ./gateway-service
    container_name: myapp-gateway-service
    ports:
      - "8080:8080"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      config-service:
        condition: service_healthy

#  front-end-angular:
#    build: ./angular-front-app
#    container_name: myapp-front-end-angular
#    ports:
#      - "80:80"

