spring:
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path= /customers/**
        - id: product_route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path= /products/**
